# Generated by Django 4.2.2 on 2023-06-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('ID_Usuario', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.TextField(max_length=155)),
                ('Idade', models.IntegerField()),
            ],
        ),
    ]
